spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/meta_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: false      # 운영 환경에서는 보통 false로 설정
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: dm-redis
      port: 6379
  kafka:
    bootstrap-servers: ${REDPANDA_HOST}:9092

app:
  oauth2:
    providers:
      google:
        clientId: ${GOOGLE_CLIENT_ID}
        clientSecret: ${GOOGLE_CLIENT_SECRET}
        redirectUri: "https://api.letzgo.site/rest-api/v1/oauth2/google"
        tokenUri: "https://oauth2.googleapis.com/token"
        userInfoUri: "https://www.googleapis.com/oauth2/v3/userinfo"
      naver:
        clientId: ${NAVER_CLIENT_ID}
        clientSecret: ${NAVER_CLIENT_SECRET}
        redirectUri: "https://api.letzgo.site/rest-api/v1/oauth2/naver"
        tokenUri: "https://nid.naver.com/oauth2.0/token"
        userInfoUri: "https://openapi.naver.com/v1/nid/me"
      kakao:
        clientId: ${KAKAO_CLIENT_ID}
        redirectUri: "https://api.letzgo.site/rest-api/v1/oauth2/kakao"
        tokenUri: "https://kauth.kakao.com/oauth/token"
        userInfoUri: "https://kapi.kakao.com/v2/user/me"

frontend:
  oauth-redirect: https://www.letzgo.site/login

fcm:
  service-account-file: file:/app/fcm-private-key.json
  project-id: 910298565199

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    config-url: /v3/api-docs/swagger-config
    url: /v3/api-docs
    groups-order: DESC
    operations-sorter: method
    tags-sorter: alpha
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

logging:
  level:
    org.springframework.web: INFO
    team.iedu: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN



#RedPanda

#version: '3.8'
#
#services:
#  redpanda:
#    image: docker.redpanda.com/redpandadata/redpanda:latest
#    container_name: redpanda-0
#    restart: unless-stopped
#    command:
#      - redpanda
#      - start
#      - --mode
#      - dev-container
#      - --smp
#      - "1"
#      - --memory
#      - 256M
#      - --reserve-memory
#      - 128M
#      - --default-log-level=warn
#      - --kafka-addr
#      - PLAINTEXT://0.0.0.0:9092
#      - --advertise-kafka-addr
#      - PLAINTEXT://175.45.192.38:9092
#      - --pandaproxy-addr
#      - 0.0.0.0:8082
#      - --advertise-pandaproxy-addr
#      - 175.45.192.38:8082
#      - --schema-registry-addr
#      - 0.0.0.0:8081
#      - --rpc-addr
#      - 0.0.0.0:33145
#      - --advertise-rpc-addr
#      - 175.45.192.38:33145
#    ports:
#      - "9092:9092"     # Kafka API
#      - "8081:8081"     # Schema Registry
#      - "8082:8082"     # PandaProxy
#      - "9644:9644"     # Admin API
#    volumes:
#      - redpanda_data:/var/lib/redpanda/data
#    networks:
#      - redpanda_network
#
#volumes:
#  redpanda_data:
#
#networks:
#  redpanda_network:
#    driver: bridge
